apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: boti95/linux_tweet_app:2.0  # Ensure the image is correct for your app
        ports:
        - containerPort: 80  # Expose port 80 for HTTP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf  # Mount the custom Nginx config file
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
        - -nginx.scrape-uri=http://127.0.0.1/status
        ports:
        - containerPort: 9113
          name: metrics
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config  # Use the ConfigMap with the updated Nginx config


