apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80  # Expose HTTP on port 80
    targetPort: 80  # Map it to the container's port 80
  - name: https
    protocol: TCP
    port: 443  # Expose HTTPS on port 443 (if needed)
    targetPort: 443  # Map it to the container's port 443
  - name: metrics
    protocol: TCP
    port: 9113
    targetPort: 9113
  type: NodePort

