apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: "ClusterIP"
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32426
  selector:
    app: grafana