apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana
  labels:
    app: grafana
spec:
  type: {{ .Values.grafana.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.grafana.service.port | default 3000 }}
      targetPort: 3000
      nodePort: {{ .Values.grafana.service.NodePort | default 32426 }}
  selector:
    app: grafana