apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: nginx
spec:
  type: {{ .Values.nginx.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port:  80
      targetPort: 80
      nodePort: 32377
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 32378
  selector:
    app: nginx