apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - name: http
      port:  80
      targetPort: 80
      nodePort: 32377
    - name: metrics
      port: 9113
      targetPort: 9113
      nodePort: 32378
  selector:
    app: nginx