apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app: prometheus
spec:
  type: {{ .Values.prometheus.service.type | default "ClusterIP" }}
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30990
  selector:
    app: prometheus